export const imagePaths: string[] = [
  "/portfolio/patterns/main_w1 2.jpg",
  "/portfolio/patterns/pattern6.jpg",
  "/portfolio/patterns/horseshoecrab.jpg",
  "/portfolio/patterns/diatoms.png",
  "/portfolio/patterns/kennamain_pattern_1.jpg",
  "/portfolio/patterns/radiolarian.png",
  "/portfolio/patterns/cuttlefish.png",
  "/portfolio/metamorphic/main_metamorphic.png",
  "/portfolio/metamorphic/TRANSFORMER poster.png",
  "/portfolio/metamorphic/shapeshifter poster.png",
  "/portfolio/metamorphic/metamorphic poster final.png",
  "/portfolio/Gauache/main_poster_art.jpg",
  "/portfolio/bookstore/bookposter2.png",
  "/portfolio/bookstore/bookposter3.png",
  "/portfolio/bookstore/bookposter1.png",
  "/portfolio/bookstore/Three_Posters_In_Metal_Frames.jpg",
  "/portfolio/make_a_discovery/make4.png",
  "/portfolio/make_a_discovery/make5.png",
  "/portfolio/make_a_discovery/make7.png",
  "/portfolio/make_a_discovery/make6.png",
  "/portfolio/make_a_discovery/make2.png",
  "/portfolio/make_a_discovery/makefront.png",
  "/portfolio/make_a_discovery/make3.png",
  "/portfolio/make_a_discovery/IMG_7681.HEIC",
  "/portfolio/make_a_discovery/IMG_7678.HEIC",
  "/portfolio/make_a_discovery/make.glb",
  "/portfolio/park_wayfinding/softball4.png",
  "/portfolio/park_wayfinding/softball3.png",
  "/portfolio/park_wayfinding/softball2.png",
  "/portfolio/park_wayfinding/softball1.png",
  "/portfolio/park_wayfinding/park_signs.png",
  "/portfolio/pompeiiworm_inforgraphic/pompeii infographic.pdf",
  "/portfolio/lbtp/lbtp_direwolf_sticker.png",
  "/portfolio/lbtp/KennaMain_TshirtMockupfront_ 2.jpg",
  "/portfolio/lbtp/lbtp_poster.png",
  "/portfolio/lbtp/KennaMain_PinMockup.jpg",
  "/portfolio/lbtp/KennaMain_TicketMockup.jpg",
  "/portfolio/lbtp/lbtp_wordlockup.svg",
  "/portfolio/lbtp/KennaMain_TshirtMockupback_2.jpg",
  "/portfolio/lbtp/KennaMain_ToteBag_Mockup_2.jpg",
  "/portfolio/lbtp/lbtp_symbol.svg",
  "/portfolio/lbtp/KennaMain_Sticker_Mockup_2.jpg",
  "/portfolio/lbtp/KennaMain_ToteBag_Mockup_1.jpg",
  "/portfolio/lbtp/KennaMain_cardmockup_2.jpg",
  "/portfolio/lbtp/KennaMain_cardmockup_1.jpg",
  "/portfolio/lbtp/KennaMain_StickerMockup.1.jpg",
  "/portfolio/book/book_illustrations.png",
  "/portfolio/book/bookcover.glb",
  "/portfolio/science_illustrations/cicada.png",
  "/portfolio/science_illustrations/marine_worm.png",
  "/portfolio/science_illustrations/lynx_spider.png",
  "/portfolio/science_illustrations/florida_insects.png",
  "/portfolio/newsletter/makingwherever.png",
  "/portfolio/newsletter/whoiam.png",
  "/portfolio/newsletter/front.png",
  "/portfolio/psa/psa_3.jpg",
  "/portfolio/psa/psa_2.jpg",
  "/portfolio/psa/psa_1.jpg",
]